### ISSUE TITLE
exports.createAntenna does not handle special characters

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#3]
There is no handling of special alphabets such as:
- Greek
- Cyrillic
- Azeri
- Others?

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/3
- Originally reported by: [grasshopper](http://bitbucket.org/grasshopper)
- Originally created at: 2015-05-25T18:03:26.289

**Comment by ingomueller-net** [comment]
ok actually I realised I still have to implement this method lol

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by linuxbandit** [comment]
So if you modify this method, please notice that:
- the attribute "netcom" [(find here)](https://github.com/AEGEE/oms-core/blob/dev/lib/core.js#L196) should be renamed into "supervisor"
- upon handling of non-ASCII characters, one could also add into the payload (i.e. the "entry") the attribute bodyName

Again, you don't have to learn LDAP, if it's unclear is just because I couldn't explain myself properly and not because you don't have the necessary knowledge!
