### ISSUE TITLE
IDs for Antennae, Users, ...

### ISSUE THREAD

**Issue by blacksph3re** [AEGEE/oms-core#57]
Right now the IDs for a user are represented by something like "cave.johnson" and an antenna is represented by it's body code like "ADA". Maybe it would be easier to just use integers for that?

**Comment by linuxbandit** [comment]
2 Questions:

What about when you have a deleted antenna? The number goes missing

What about when you found the antenna again (e.g. Dresden did so)? Would you reassign the ID or start with a new one?

**Comment by blacksph3re** [comment]
There are 18446744073709551615 possible numbers until overflow, so of course take a new one and yes, let them go missing :D Just have an atomic counter somewhere for the next number to be assigned and you're in. 
Illustrated: If we get a new antenna every second, it would take 0.5 trillion years to use all the numbers ;-)
Advantages: 
- You can change the loginname if you want
- Infinitely many numbers until conflict while there might be a second "cave.johnson" somewhere and you would have to search the database on creation
- (Faster DB lookup)? I don't know how LDAP is working but with SQL an integer-id is the fastest access you can get, usually O(1)
- Can be distinguished from a string if part of a request
- More beautiful?

But it would also work with your strings, I was just wondering while studing your api... =)

**Comment by linuxbandit** [comment]
> until overflow

haha that was not my concern, I mean, for integrity perhaps you don't want a Dresden being ID = 10 one time and after 3 years with ID = 2032?

however now I understand that I misunderstood your question at all, I thought you were just talking about the antennae because this 3 letter algorithm could be flunky. I will comment later as I have a job interview now, but very in short I will tell you that I thought of replicating usernames (cave.johnson) into a sql table: this data has to be relational clearly, so a sync between ldap-sql could be in the picture

**Comment by blacksph3re** [comment]
> for integrity

Well, if it's the same local and stuff in the system is still linked to it, you could also just reuse the db entry with the same id.

And yes, I meant both antennae and users. And I did not at all understand what you meant with that ldap-sql thing, but it sounds really weird... however, should I code my service with integers or with numbers as references to your service?
